### ISSUE TITLE
data is readable in azure powershell but not recieved in stream anlytics job says that no data in iot hub

### ISSUE THREAD

**Issue by Amitjipathak** [Azure-Samples/azure-iot-samples-python#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create an issue on [azure-iot-sdk-python](https://github.com/Azure/azure-iot-sdk-python) if needed.
