### ISSUE TITLE
Method request handler exceptions not handled.

### ISSUE THREAD

**Issue by yvanbo** [Azure-Samples/azure-iot-samples-python#35]
### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Download `iot-hub/Quickstarts/simulated-device-2/SimulatedDeviceAsync.py`
1. Add raising an exception to the bottom of `method_request_handler` (after line 44; e.g. `raise Exception("new exception")`)
1. Run the sample.

### Any log messages given by the failure
> Exception caught in background thread.  Unable to handle.
> ['azure.iot.device.iothub.sync_handler_manager.HandlerManagerException: HANDLER (CLIENT_EVENT): Error during invocation\n']

### Expected/desired behavior
- The `try/except` statements starting line 46 suggest that it should catch any exception within `method_request_handler`, even though line 48 is only an assignment operation.
- Expected would be that upon an exception within `method_request_handler`, the `except` statements are executed, i.e. the client shutdown.
- Ideally, the main coroutine (`run_telemetry_sample`) would be gracefully shutdown by this as well.

### OS and Version?
> macOS Catalina 10.15.7

### Versions
> Python 3.10.8
> azure-core 1.26.2
> azure-iot-hub 2.6.1
> azure-iot-device 2.12.0

**Comment by ryanwinter** [comment]
Only exceptions are caught during the assignment of the handler, not during execution after connection.

Closing as repository is being archived. Please create an issue on [azure-iot-sdk-python](https://github.com/Azure/azure-iot-sdk-python) if needed.
