### ISSUE TITLE
Direct method name shortened

### ISSUE THREAD

**Issue by FluxReality** [Azure-Samples/azure-iot-samples-python#5]
### This issue is for a: 
```
- [ x] bug report 
```
### Minimal steps to reproduce
> Using Python 3.5.4 on Windows 10 Run the example 
Quickstarts/simulated-device-2/SimulatedDevice.py
and 
Quickstarts/back-end-application/BackEndApplication.py

Using a vallid connection string.

### Any log messages given by the failure
From the SimulatedDevice.py log:
```
Method callback called with:
methodName = SetTelem
payload = 10
Response: { "Response": "Direct method not defined: SetTelem" }Status: 404IoT Hub responded to message with status: OK
```
BackEndApplication.py log:

```
Device Method called
Device Method name       : SetTelemetryInterval
Device Method payload    : 10

Response status          : 404
Response payload         : {"Response":"Direct method not defined: SetTelem"}
Press Enter to continue...
```

### Expected/desired behavior
> Expected 
`Status: 200Sending message: {"temperature": 24.43,"humidity": 68.90}`

### OS and Version?
> Windows 10

### Versions
> Latest commit 7a5a959 on May 22 of this repository, and
version 1.4.0 of azure-iothub-device-client

### Mention any other details that might be useful

Shortening the direct method name expected and used, lets the system work as designed. This indicates that the problem might be in the API's handling of strings from python into the underlying libraries. Perhaps a buffer-overflow issue?

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create an issue on [azure-iot-sdk-python](https://github.com/Azure/azure-iot-sdk-python) if needed.
