### ISSUE TITLE
Issue running through documentation for BackEndApplication

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure-Samples/azure-iot-samples-python#7]
Hello,

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
```

### Minimal steps to reproduce
> I'm walking through this:  https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-control-device-python

### Any log messages given by the failure
>  See output below

### Expected/desired behavior
> I would expect it not to crash.

### OS and Version?
> OSX  10.13.6

It appears that the C code library has an issue with the Python hook into it.

```
➜  back-end-application git:(master) ✗ python3 BackEndApplication.py
IoT Hub Python quickstart #2...
    Connection string = HostName=thelab-iot-hub.azure-devices.net;DeviceId=MyPythonDevice;SharedAccessKey=<removed>
    Device ID         = MyPythonDevice
Going to connect
Error: Time:Fri Oct 12 15:12:15 2018 File:/Users/trashcan/release/azure-iot-sdk-python/c/iothub_service_client/src/iothub_devicemethod.c Func:IoTHubDeviceMethod_Create Line:392 authInfo->keyName input parameter cannot be NULL

Unexpected error IoTHubDeviceMethod.IoTHubDeviceMethod, IoTHubDeviceMethodResult.ERROR

➜  back-end-application git:(master) ✗ pip3 install azure-iothub-service-client future
Requirement already satisfied: azure-iothub-service-client in /usr/local/lib/python3.7/site-packages (1.4.3)
Requirement already satisfied: future in /usr/local/lib/python3.7/site-packages (0.16.0)
```

**Comment by MaWa19** [comment]
Maybe a bit late, but it seems like you're using the access key of a specific device instead of the service access key which can be found in your IoT Hub under 'Shared access policies'.
That's why the error message says 'keyName' cannot be NULL.

**Comment by yzhong94** [comment]
That's right, you need to use the service connection string.  Please see step three here: https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-control-device-python#register-a-device
