### ISSUE TITLE
Request: Python firmware update sample.

### ISSUE THREAD

**Issue by pierreca** [Azure-Samples/azure-iot-samples-python#9]
This is a request to have a python sample covering this scenario:
https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-firmware-update

Original issue: https://github.com/Azure/azure-iot-sdk-python/issues/243

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create an issue on [azure-iot-sdk-python](https://github.com/Azure/azure-iot-sdk-python) if needed.
